// <auto-generated />
using System;
using System.Collections.Generic;
using HireServices.Features.ServiceProviders.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HireServices.Migrations.ProviderDb
{
    [DbContext(typeof(ProviderDbContext))]
    [Migration("20241226224657_AddNullTypeToAverageRating")]
    partial class AddNullTypeToAverageRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HireServices.Features.ServiceProviders.Domain.AggregateRoots.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomersServed")
                        .HasColumnType("int");

                    b.Property<string>("HighlightedServices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LatestReviews")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("ServiceCategories")
                        .IsRequired()
                        .HasColumnType("TEXT[]");

                    b.PrimitiveCollection<List<string>>("ServiceTags")
                        .IsRequired()
                        .HasColumnType("TEXT[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategories");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ServiceCategories"), "gin");

                    b.HasIndex("ServiceTags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ServiceTags"), "gin");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("HireServices.Features.ServiceProviders.Domain.AggregateRoots.ProviderService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId1");

                    b.ToTable("ProviderServices");
                });

            modelBuilder.Entity("HireServices.Features.ServiceProviders.Domain.AggregateRoots.Provider", b =>
                {
                    b.OwnsOne("HireServices.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ProviderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("ProviderId");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("HireServices.Features.ServiceProviders.Domain.AggregateRoots.ProviderService", b =>
                {
                    b.HasOne("HireServices.Features.ServiceProviders.Domain.AggregateRoots.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireServices.Features.ServiceProviders.Domain.AggregateRoots.Provider", null)
                        .WithMany("ProviderServices")
                        .HasForeignKey("ProviderId1");
                });

            modelBuilder.Entity("HireServices.Features.ServiceProviders.Domain.AggregateRoots.Provider", b =>
                {
                    b.Navigation("ProviderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
